### ISSUE TITLE
Cherry Bomb Oddities

### ISSUE THREAD

**Issue by nednaZ** [Monkestation/MonkeStation#234]
A Cherry Bomb appears to detonate at the point it was lit, not the point that it actually should detonate at.
Same issue that Oil Slime Grenades had?

**Comment by KoboldCommando** [comment]
Similar but different to oil grenades.  I'll try to get to this sooner rather than later.  I believe the underlying issue is that cherry bombs are being treated as if they're open beakers, i.e. when the black powder reacts it bubbles out and reacts on the floor.

Cherry bombs should instead be a closed container that keeps hold of the reacting ingredients even while moved.  I think the in-progress-explosion code needs to be updated to check and handle this.

**Comment by dwasint** [comment]
was fixed
