### ISSUE TITLE
Crew Monitor sometimes just doesn't show people with maxxed sensors

### ISSUE THREAD

**Issue by unit0016** [Monkestation/MonkeStation#411]
Issue reported from  Round ID: 1023 (Monkestation)

Reporting client version: 514.1584

See title. Even applies for those with monitoring nanites.

**Comment by ThePooba** [comment]
Any idea how to reproduce the bug?

**Comment by unit0016** [comment]
> Any idea how to reproduce the bug?

Unknown. Just kinda.. happens with monitoring nanites or maxxed sensors.

**Comment by MilkForever** [comment]
I found out that turning off your suit sensors and setting them back on will make you appear on the crew monitor (until the crew monitor decides to give up and not show anyone at all).

This is still a pretty big issue since medical won't be able to tell if someone is dead or not even if they have their suit sensors on.
